### ISSUE TITLE
Task: 重命名VerifyData

### ISSUE THREAD

**Issue by Shareong** [WeBankFinTech/WeCross#271]
类[VerifyData](https://github.com/WeBankFinTech/WeCross/blob/master/src/main/java/com/webank/wecross/routine/htlc/VerifyData.java)功能非常简单，保存待验证的数据，并提供一个接口与期望的数据进行对比。目前的类名似乎不太规范，帮忙贡献一个更好的名字吧。

**Comment by chenjiawei514** [comment]
DataValidator

**Comment by Shareong** [comment]
> DataValidator

感谢，项目已采纳。
