### ISSUE TITLE
Task: Remove unused class `TransactionManager`

### ISSUE THREAD

**Issue by morebtcg** [WeBankFinTech/WeCross#274]
WeCross项目内，[com.webank.wecross.transaction](https://github.com/WeBankFinTech/WeCross/tree/master/src/main/java/com/webank/wecross/transaction)包的TransactionManager类，没有被任何类使用，请将这个类及其代码文件移除，并确认对其他功能没有影响。

**Comment by JimmyShi22** [comment]
#293
