### ISSUE TITLE
跨链事务问题咨询

### ISSUE THREAD

**Issue by fenQY** [WeBankFinTech/WeCross#294]
**BUG描述**
简要描述 BUG 的表现，造成的影响。
执行 ：
> newHTLCTransferProposal payment.bcos.htlc bcos 5405166a2bfc5d1eddf25625b4e8595f40d446243966f1d5786bab272bb12958 ec775276eb6df852988a94cedbd6f8275fdd093ce7d134e1c1aa2bede7f4e0f7 true 0x55f934bcbe1e9aef8337f5551142a442fdde781c 0x2b5ad5c4795c026514f8317c7a215e218dccd6cf 700 1593485531 Admin@org1.example.com User1@org1.example.com 500 1593485231

响应：
Response{
 version='1',
 errorCode=52000,
 message='Account is null',
 data=null
}

问题1：
     上述问题是否为接受者地址不存在造成？该地址该如何生成？

问题2：
      事务案例中的部署流程缺少用户配置相关细节描述， 接入是借鉴手动组网中的方式嫁接过来操作的是否会存在问题？

**Comment by Shareong** [comment]
你好。

问题1：
创建提案本质上也是发交易，需要指定账户，因此该现象是因为**发交易**的账户即**bcos**不存在造成的，你可以在控制台通过listAccounts查看已配置好的账户。需要注意的是，创建HTLC提案的账户必须和该链的资产转出者账户一致，根据你的命令该账户地址为0x55f934bcbe1e9aef8337f5551142a442fdde781c。具体账户配置方法及注意事项可参阅[哈希时间锁定合约配置章节](https://wecross.readthedocs.io/zh_CN/latest/docs/routine/htlc.html#id3)。

问题2：
没有影响，手动组网也是搭建环境的一种方式，在这之上配置HTLC是没有任何问题的。关于缺少用户配置细节描述，不知是具体哪一步，配置哪一项还有疑问，麻烦指出，我们尽快完善哈。

**Comment by fenQY** [comment]
回复问题1:

合约地址：0x9d5de31f1c52b9e0a866cb60f344b68d11326d5f

ledger-tool：
assetAddress: 0x3e8e1e8d878e185d0fd816293766888cae3808aa
owner: 0x55f934bcbe1e9aef8337f5551142a442fdde781c

bcos的路由配置：
# accounts ###############################################
accounts/
├── bcos_user1
│   ├── account.key
│   └── account.toml
├── bcos_user2
│   ├── account.key
│   └── account.toml
└── fabric_admin
    ├── account.crt
    ├── account.key
    └── account.toml

#chains #################################################
chains
└── bcos
    ├── ca.crt
    ├── node.crt
    ├── node.key
    ├── sdk.crt
    ├── sdk.key
    └── stub.toml

#### bcos配置：########################################
[[resources]]
    # name cannot be repeated
    name = 'htlc'
    type = 'BCOS_CONTRACT'
   #本机的合约地址
    contractAddress = '0x9d5de31f1c52b9e0a866cb60f344b68d11326d5f‘

#### wecross.toml 配置   ################################
[[htlc]]
     #本地配置的哈希时间锁资源路径
    selfPath = 'payment.bcos.htlc'

    #确保已在router的accounts目录配置了bcos_default_account账户
    account1 = 'bcos_user1'

    #对手方的哈希时间锁资源路径
    counterpartyPath = 'payment.fabric.htlc'

    #确保已在router的accounts目录配置了fabric_default_account账户
    account2 = 'fabric_admin'


[WeCross]> listAccounts
name: fabric_admin, type: Fabric1.4
name: bcos_user1, type: BCOS2.0
name: bcos_user2, type: BCOS2.0
total: 3

fabric在另外一个路由中配置的这里省略，只贴出了bcos的部分，是这样么？ listAccounts没法查到那个16进制的地址。

**Comment by fenQY** [comment]
回复问题2：
     不太能确定的地方
      1.就是 [[htlc]] 中的account2 是要配置跨链对方的用户， 该用户是否直接将对方链的用户证书cp到当前路由的account目录下？
      2.该案例配置是要和手动组网中一样“一个路由配一条链“， 还是需要将bcos和fabric俩条链的信息都配在同一个路由下的 
     chains中？

**Comment by Shareong** [comment]
1. 你需要将ledger-tool的conf目录下的pem文件配置到连接bcos链的路由的accounts目录下，这才是真正参与资产兑换的账户。
2. wecross.toml中htlc配置的account1和account2你可以理解成工具账户，路由协调htlc的时候需要在两条链发交易，因此要给它配两个账户，这两个账户可以直接通过脚本工具生成。
3. 是否把两条链配在一个路由，这个是业务决定的，和htlc没关系，它都支持。

**Comment by fenQY** [comment]
有些蒙圈, 按照文档指引不是应该将bcos节点sdk目录下的证书配置到ledger-tool中么?  
能否加您的微信指导一下呢?

**Comment by Shareong** [comment]
其实文档里是有介绍的哦。
你有加微众区块链群吗，可以通过添加小助手wxid_mpute7a2noqc12进群，然后找Shuanghong He就是我啦。
