### ISSUE TITLE
macOS下使用demo/build.sh搭建Demo失败

### ISSUE THREAD

**Issue by kyonRay** [WeBankFinTech/WeCross#322]
**BUG描述**
macOS下快速搭建Demo失败，错误发生在`demo/build.sh`脚本32行。

在`config_bcos_stub_toml`函数中130行，调用`sed_i`函数，发生如下错误：
```shell
sed: can't read 16,20d: No such file or directory
```
`sed_i`改成`sed -i`即可。

**Comment by JimmyShi22** [comment]
👍 下版本修复此问题
