### ISSUE TITLE
为什么运行demo时出现WeCrossProxy has not been deployed to: [Org1, Org2]的错误？

### ISSUE THREAD

**Issue by bigrance** [WeBankFinTech/WeCross#361]
**Describe the bug**
错误如下
WeCross start failed
See logs/error.log for details
Error log
2020-09-21 23:38:17.348 [main] ERROR FabricStubFactory() - newConnection exception: java.lang.Exception: WeCrossProxy has not been deployed to all org
2020-09-21 23:38:17.349 [main] ERROR ZonesConfig() - Init localConnection: classpath:chains/fabric-Fabric1.4 failed
2020-09-21 23:38:17.349 [main] ERROR ZonesConfig() - Init localConnection failed
Start log

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.1.13.RELEASE)

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/demo/demo/routers-payment/127.0.0.1-8251-25501/lib/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/demo/demo/routers-payment/127.0.0.1-8251-25501/plugin/bcos2-stub-1.0.0-rc4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/demo/demo/routers-payment/127.0.0.1-8251-25501/plugin/bcos2-stub-gm-1.0.0-rc4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Load classpath:wecross.toml ...
Initializing StubManager...
Initializing ZoneMap ...
WeCrossProxy has not been deployed to: [Org1, Org2]
Usage:
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment check [chainName]
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment deploy [chainName]
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment upgrade [chainName]
Example:
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment check chains/fabric
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment deploy chains/fabric
         java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment upgrade chains/fabric

**Comment by bigrance** [comment]
救救孩子吧，搭了一天了还不成功

**Comment by JimmyShi22** [comment]
报错的提示是代理合约未部署，给出了代理合约部署的命令。
是执行build.sh之后报错的么？

**Comment by bigrance** [comment]
> 报错的提示是代理合约未部署，给出了代理合约部署的命令。
> 是执行build.sh之后报错的么？

是的，就是在执行这个命令之后

**Comment by bigrance** [comment]
> 报错的提示是代理合约未部署，给出了代理合约部署的命令。
> 是执行build.sh之后报错的么？

我又使用手动组网，然后执行到部署代理chaincode这一步，也就是java -cp 'conf/:lib/*:plugin/*' com.webank.wecross.stub.fabric.proxy.ProxyChaincodeDeployment deploy chains/fabric命令时，依然出现了下面的错误：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/wecross/routers-payment/127.0.0.1-8251-25501/lib/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/wecross/routers-payment/127.0.0.1-8251-25501/plugin/bcos2-stub-1.0.0-rc4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/wecross/routers-payment/127.0.0.1-8251-25501/plugin/bcos2-stub-gm-1.0.0-rc4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
WeCrossProxy has not been deployed to: [Org1, Org2]
path: classpath:chains/fabric/WeCrossProxy/
Install WeCrossProxy:1600742567 to Org1 ...
path: classpath:chains/fabric/WeCrossProxy/
Install WeCrossProxy:1600742567 to Org2 ...
Instantiating WeCrossProxy:1600742567 to [Org1, Org2] ...
java.util.concurrent.TimeoutException

**Comment by bigrance** [comment]
> 报错的提示是代理合约未部署，给出了代理合约部署的命令。
> 是执行build.sh之后报错的么？

**Comment by bigrance** [comment]
单独运行两条链也都能部署成功，就是wecross连不起来

**Comment by bigrance** [comment]
在服务器和虚拟机上都出现了这个问题

**Comment by bigrance** [comment]
有大佬嘛，帮忙看一下

**Comment by JimmyShi22** [comment]
在Fabric上部署proxy超时了。
在这个情况下，实际上还是在部署中的，用docker ps查看一下，等到docker ps能查看到有WeCrossProxy的容器启动了，然后再启动router

**Comment by JimmyShi22** [comment]
如果router连不上，确认几个问题：
1. 网络是否通，端口是否能访问到（可以将p2p的ip改成0.0.0.0，重启router后试试）
2. router下的证书是否正确配置

**Comment by bigrance** [comment]
> 如果router连不上，确认几个问题：
> 
> 1. 网络是否通，端口是否能访问到（可以将p2p的ip改成0.0.0.0，重启router后试试）
> 2. router下的证书是否正确配置

**Comment by bigrance** [comment]
> 如果router连不上，确认几个问题：
> 
> 1. 网络是否通，端口是否能访问到（可以将p2p的ip改成0.0.0.0，重启router后试试）
> 2. router下的证书是否正确配置

我等docker生成了之后再去启动router还是不行，使用lsof -i:8051发现端口拒绝访问，那我应该如何更改p2p的ip为0.0.0.0呢

**Comment by bigrance** [comment]
> 如果router连不上，确认几个问题：
> 
> 1. 网络是否通，端口是否能访问到（可以将p2p的ip改成0.0.0.0，重启router后试试）
> 2. router下的证书是否正确配置

而且我发现配置接入FISCO BCOS链时部署代理合约可以成功，就是在fabric上部署proxy有问题

**Comment by JimmyShi22** [comment]
相应router的conf目录，修改wecross.toml，rpc和p2p都改一下吧：
``` toml
[rpc] # rpc ip & port
    address = '0.0.0.0'

[p2p]
    listenIP = '0.0.0.0'
```

改完后重启router

**Comment by bigrance** [comment]
> 相应router的conf目录，修改wecross.toml，(rpc和p2p都改一下吧，其它不变)
> 
> ```toml
> [rpc] # rpc ip & port
>     address = '0.0.0.0'
> 
> [p2p]
>     listenIP = '0.0.0.0'
> ```
> 
> 改完后重启router

还是不行，但是我发现我的服务器配置好像不满足最低要求，这样会有影响吗？
还有就是在步骤中搭建Fabric链完成后使用docker ps 查看容器状态以后和示例不一样,操作说明有这样几个容器：
dev-peer1.org2.example.com-mycc-1.0-26c2ef32838554aac4f7ad6f100aca865e87959c9a126e86d764c8d01f8346ab    "chaincode -peer.add…"   
dev-peer0.org1.example.com-mycc-1.0-384f11f484b9302df90b453200cfb25174305fce8f53f4e94d45ee3b6cab0ce9   "chaincode -peer.add…"
而我没有这几个，在执行到在Fabric上部署proxy超时后，才会出现这样的容器：
dev-peer0.org2.example.com-wecrossproxy-1601195988-4206453df40b883ef525d424d63476c14defad14d1714350d38b00f32fbdf254                                          "chaincode -peer.add…"     
 dev-peer0.org2.example.com-wecrossproxy-1601194777-f6130ed124eac384230f932b182ab30da870fb765de5e5cab054fd52101b638a                                         "chaincode -peer.add…"

**Comment by bigrance** [comment]
> 相应router的conf目录，修改wecross.toml，(rpc和p2p都改一下吧，其它不变)
> 
> ```toml
> [rpc] # rpc ip & port
>     address = '0.0.0.0'
> 
> [p2p]
>     listenIP = '0.0.0.0'
> ```
> 
> 改完后重启router
我服了我自己，就是配置的原因，换了个好一点儿的服务器就OK了，感谢大佬不厌其烦的为我解答，终于解决了

**Comment by 2681413174** [comment]
把接入那一步编译项目生成的jar拷贝到相对应的router/plugin下
