### ISSUE TITLE
Task: macos 默认没有md5sum

### ISSUE THREAD

**Issue by jzhe886** [WeBankFinTech/WeCross#402]
**BUG描述**
macos 默认没有md5sum

**重现方式**
重现 BUG 的操作步骤。
例如：
1. 下载 '...'
2. 执行脚本 '....'
3. 输入控制台命令 '....'
4. 查询余额 '....'

**预期结果**
详细描述上述操作的预期结果。

**截图**
![image](https://user-images.githubusercontent.com/17755623/100092580-43596600-2e91-11eb-81eb-f98a33d7d5e1.png)

**环境**
 - 操作系统: [例如 Ubuntu、CentOS、MACOS]
 - 运行库 [例如 libc, java ]
 - 版本 [操作系统和运行库的版本]

**更多信息**
关于该 BUG 的更多信息

**Comment by JimmyShi22** [comment]
是bug 👍  ！如果mac中没有md5sum，会报错，需增加Mac的支持。

**Comment by JimmyShi22** [comment]
推荐修改方法：
脚本前增加对md5sum是否安装的检查，若未安装，则报错，提示用户安装。检查逻辑可参考：
https://github.com/WeBankFinTech/WeCross/blob/eb7bb5002b61638ce34d072d4d72e149fae93976/demo/build.sh#L38-L45

https://github.com/WeBankFinTech/WeCross/blob/eb7bb5002b61638ce34d072d4d72e149fae93976/demo/build.sh#L102-L104
