### ISSUE TITLE
问题:WeCrossProxy chaincode容器的关系是什么

### ISSUE THREAD

**Issue by zhaoquFight** [WeBankFinTech/WeCross#408]
![57U84M295Z 3I@10M_J9MET](https://user-images.githubusercontent.com/35955830/100494535-b0b11380-317d-11eb-8090-0dea9b2e96ab.png)

我尝试关闭sacc容器 在wecross-console调用链码时 容器会重新启动 我猜测他们是有关系的。

想问下 生成的这4个容器 有什么关系 ？ 我依然可以像Fabric去调用sacc 但是我并不太了解WeCrossProxy是怎么工作的。

刚接触wecross希望能够解答 谢谢

**Comment by JimmyShi22** [comment]
WeCrossProxy 是WeCross调用的总入口，所有的调用都走到WeCrossProxy，再invokeChaincode到相应的chaincode上

**Comment by JimmyShi22** [comment]
手动关闭chaincode的容器，在被调用时会自动拉起

**Comment by zhaoquFight** [comment]
> WeCrossProxy 是WeCross调用的总入口，所有的调用都走到WeCrossProxy，再invokeChaincode到相应的chaincode上

好的 谢谢您 祝生活愉快~
