### ISSUE TITLE
[ERROR] BCOS-RPC port 8545 is not avaliable. Are there any other blockchain is running?

### ISSUE THREAD

**Issue by RookieLinLucy666** [WeBankFinTech/WeCross#411]
**BUG描述**
[ERROR] BCOS-RPC port 8545 is not avaliable. Are there any other blockchain is running?

**重现方式**
1. 停止本地运行的FISCO BCOS，`cd fisco/nodes/127.0.0.1`   `bash stop_all.sh`
2. 查看端口，`netstat -lntpu`，已经没有8545
>Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      466/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      587/sshd
tcp6       0      0 :::7946                 :::*                    LISTEN      586/dockerd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           466/systemd-resolve
udp        0      0 172.26.86.56:68         0.0.0.0:*                           24251/systemd-netwo
udp        0      0 127.0.0.1:323           0.0.0.0:*                           599/chronyd
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                599/chronyd
udp6       0      0 :::7946                 :::*                                586/dockerd
3. 运行wecross安装脚本，`bash clear.sh` `bash build.sh`
4. 报错：[ERROR] BCOS-RPC port 8545 is not avaliable. Are there any other blockchain is running?

**环境**
 - 操作系统: Ubuntu 18.04

**Comment by JimmyShi22** [comment]
已知bug，判断端口是否存在时用了netstat + grep的方式，导致8545如果是端口的子串也会判断存在。如存在18545端口，也会判断8545已存在。

修复方法：判断是否是此问题，若是，可编辑build.sh文件，将check_port_avaliable 8545注释掉

**Comment by JimmyShi22** [comment]
此问题将在v1.0.0中修复 👍

**Comment by RookieLinLucy666** [comment]
好的，感谢您的解答。😊
